### ISSUE TITLE
An error occurs when I generate the HDF files

### ISSUE THREAD

**Issue by ruclty** [DataManagementLab/restore#1]
I am going to generate the HDF files on the Airbnb dataset after preprocessing. However, an error occurs when calling the function common_element() in the /schema_setup/incomplete_schema_setup/utils.py. In line 64, np.unique() returns "TypeError: '<' not supported between instances of 'float' and 'str'".  It is solved by removing the null values in the categorical columns before calling np.unique(). I wonder if this error is caused by the package version or other environmental problems? Thank you.

**Comment by ghost** [comment]
Hi, yes you are right. This must be caused by a different package version that I used. However, since this is just for logging anyways, we can also skip this part if it is problematic. I have pushed a simple fix.
